#### 001 Numpy
- NumPy (Numerical Python) is an open-source library in Python designed for numerical computation.
- It provides high-performance tools for working with arrays, matrices, and a large collection of mathematical functions to operate on these data structures.

##### Key features

- Multi-Dimensional Arrays: 
    The core data structure of NumPy is the ndarray (n-dimensional array), which is efficient and supports multi-dimensional data.
- Mathematical Functions: 
    NumPy provides functions for basic arithmetic, trigonometry, statistical operations, and linear algebra.
- Broadcasting: 
    Enables element-wise operations on arrays of different shapes and sizes, avoiding the need for explicit loops.
- Efficient Computation: 
    Operations on NumPy arrays are performed in C, making them much faster than equivalent Python operations on lists.
- Integration with Other Libraries: 
    NumPy is foundational to other scientific computing libraries like SciPy, Pandas, and TensorFlow.

#### 002 Explanation and Use Cases

##### Array Manipulation
- NumPy arrays (ndarray) are similar to Python lists but allow element-wise operations, slicing, reshaping, and more.
Example: np.array([1, 2, 3]) creates a 1-dimensional array.

##### Mathematical Computation
- Includes functions for:
        Arithmetic (np.add, np.multiply)
        Trigonometry (np.sin, np.cos)
        Statistics (np.mean, np.std)
        Linear algebra (np.dot, np.linalg.inv)

##### Data Analysis
- Used extensively in pre-processing datasets, performing statistical analysis, and handling large data volumes.

##### Scientific Computing
- Widely used in engineering, physics, and bioinformatics for simulations and numerical modeling.

##### Machine Learning
- Foundational in frameworks like TensorFlow and PyTorch for numerical back-end computations.

##### Image Processing
- Handles image arrays for transformations, filtering, and manipulation.

#### Importance of NumPy

- Performance:
    NumPy is much faster than standard Python operations due to its use of optimized C libraries for array operations.

- Ease of Use:
    Its clean syntax and rich functionality simplify complex numerical tasks.

- Community and Ecosystem:
    It is the backbone of Python’s scientific computing stack, with strong community support and documentation.

- Compatibility:
    Integrates seamlessly with Python’s data ecosystem (e.g., Pandas, Matplotlib, SciPy).

- Memory Efficiency:
    Consumes less memory compared to Python lists.

#### Summary
- NumPy is a cornerstone library for numerical and scientific computing in Python.
- Its efficient array handling, extensive mathematical operations, and interoperability with other libraries make it indispensable for data science, machine learning, and other computational tasks.

#### 003 Creating Arrays

##### Definition:
- NumPy arrays, also known as ndarray (n-dimensional arrays), are the core data structure of the NumPy library. 
- They are multi-dimensional, homogeneous collections of data elements indexed by a tuple of non-negative integers. 
- Unlike Python lists, NumPy arrays are fixed in size and type, providing high performance and efficient memory use.

##### Key Characteristics of NumPy Arrays
- Homogeneity:
    - All elements in a NumPy array must have the same data type (e.g., integers, floats).
    - This uniformity allows faster computations as type checking is not repeated for each element.

- Multi-Dimensional:
    - NumPy arrays support 1D, 2D, and higher-dimensional structures.
    Example:
        1D Array: [1, 2, 3]
        2D Array: [[1, 2], [3, 4]]
        3D Array: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

- Efficient Memory Management:
    - NumPy arrays are implemented in C, reducing memory overhead and increasing performance compared to Python lists.

- Vectorized Operations:
    - Operations on arrays are element-wise and use broadcasting, eliminating the need for explicit loops.

- Indexing and Slicing: 
    - NumPy arrays support advanced indexing and slicing for efficient data access and modification.

##### 004 Explanation of NumPy Arrays

- Creating Arrays:
- NumPy arrays can be created from:
        - Python lists or tuples using np.array().
        - Functions like np.zeros(), np.ones(), np.linspace(), and np.arange().

- Shape and Dimensions
        - Each array has attributes like .shape, .size, and .ndim to indicate its structure and size.
            -Example:

            arr = np.array([[1, 2, 3], [4, 5, 6]])
            print(arr.shape)  # (2, 3)
            print(arr.ndim)   # 2

In [53]:
#### Create a numpy array 4x4 where the first diagonal is 1 and all other values are 0

import numpy as np
import svg as svg
from svg import numpy_to_svg

mylist = [2, 5, 3, 9, 5, 2]

print(mylist)

myarray = np.array(mylist)

print(myarray)

type(myarray)

ModuleNotFoundError: No module named 'svg'

In [ ]:
lst = [1, 2, 3, 4, 5]
print(lst)

arr = np.array(lst)
print(arr)

type(arr)


[1, 2, 3, 4, 5]
[1 2 3 4 5]


numpy.ndarray

In [8]:
arr.dtype

dtype('int32')

We see that ```myarray``` is a Numpy array thanks to the ```array``` specification in the output. The type also says that we have a numpy ndarray (n-dimensional). At this point we don't see a big difference with regular lists, but we'll see in the following sections all the operations we can do with these objects.

We can already see a difference with two basic attributes of arrays: their type and shape.

#### 005 Array Type

Just like when we create regular variables in Python, arrays receive a type when created. Unlike regular list, **all** elements of an array always have the same type. The type of an array can be recovered through the ```.dtype``` method:

In [9]:
myarray.dtype

dtype('int32')

#### 006 Array shape

A very important property of an array is its **shape** or in other words the dimensions of each axis. That property can be accessed via the ```.shape``` property:

In [39]:
myarray

array([2, 5, 3, 9, 5, 2])

In [40]:
myarray.shape

(6,)

our simple array has only one dimension of length 6. Now of course we can create more complex arrays. Let's create for example a *list of two lists*:

In [41]:
my2d_list = [[1,2,3], [4,5,6]]

my2d_array = np.array(my2d_list)
my2d_array

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
my2d_array.shape

(2, 3)

It's now clear, that the shape of this array is *two-dimensional*. We also see that we have 2 lists of 3 elements. In fact at this point we should forget that we have a list of lists and simply consider this object as a *matrix* with *two rows and three columns*. We'll use the follwing graphical representation to clarify some concepts:

In [1]:
numpy_to_svg(my2d_array)

NameError: name 'numpy_to_svg' is not defined

In [ ]:
zero_arr = np.zeros((2,3))

zero_arr

In [ ]:
### Create a diagonal Matrix

x = np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
#check shape
x.shape

(3, 3)

By default NumPy creates float arrays:

In [17]:
one_array = np.ones((2,3))
one_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
one_array.dtype

dtype('float64')

However as mentioned before, one can impose a type usine the ```dtype``` option:

In [20]:
one_array_int = np.ones((2,3), dtype=np.int8)
one_array_int

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

### Create a numpy array 4x4 where the first diagonal is 1 and all other values are 0.

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Copying the shape
- It is possible to create arrays of same shape. This can be done with 'like functions' 

In [22]:
same_shape_array = np.zeros_like(one_array)
same_shape_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
one_array.shape

(2, 3)

In [24]:
same_shape_array.shape

(2, 3)

In [25]:
np.ones_like(one_array)

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Complex arrays
- Complex arrays can be containing reguarly arranged numbers, eg. from-to-by-step

In [29]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

#### Or equidistant numbers between boundaries:

In [36]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

Numpy offers in particular a ```random``` submodules that allows one to create arrays containing values from a wide array of distributions. For example, normally distributed:

In [37]:
normal_array = np.random.normal(loc=10, scale=2, size=(3,4))
normal_array

array([[ 8.64035878, 10.88582455, 11.66150493,  7.94241138],
       [11.28781443,  9.4742301 , 11.08469864, 11.38082614],
       [ 7.82029898, 10.6862214 ,  8.87714472, 10.15674601]])

In [38]:
np.random.poisson(lam=5, size=(3,4))

array([[5, 4, 9, 7],
       [6, 4, 3, 7],
       [5, 4, 5, 4]])

##### Higher dimensions
